### PR TITLE
Update URL for `pmc-vip-go-plugins`

### PR DESCRIPTION
**Pull request by ethitter**
Restores #4, reverted in #5 due to hardcoded default branch

### CODE REVIEW

**Review by rnagatsukapmc — APPROVED** [review]
Just curious where `pmc_get_git_default_branch` is declared?

**Comment by ethitter** [comment]
For the moment, it's over here: https://bitbucket.org/penskemediacorp/pmc-docker-common-use-shell-scripts/src/097b0f63956e25116865bf929f147054293705b3/bin/pmc-functions#lines-3:8

That may change once we've completed the Bitbucket migration.

**Comment by rnagatsukapmc** [comment]
> For the moment, it's over here: https://bitbucket.org/penskemediacorp/pmc-docker-common-use-shell-scripts/src/097b0f63956e25116865bf929f147054293705b3/bin/pmc-functions#lines-3:8
> 
> That may change once we've completed the Bitbucket migration.

ah thanks. and I think `https://github.com/penske-media-corp/github-action-wordpress-test-setup/blob/main/scripts/add-shared-utilities.sh#L7` does the thing

**Comment by ethitter** [comment]
Yep!

**Pull request merged**
